/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package store;

import java.util.List;

/**
 *
 * @author Robert
 */
public class tblMain extends javax.swing.JFrame {

    /**
     * Creates new form tblMain
     */
    public tblMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        StorePUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("StorePU").createEntityManager();
        productstbQuery = java.beans.Beans.isDesignTime() ? null : StorePUEntityManager.createQuery("SELECT p FROM Productstb p");
        productstbList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(new java.util.LinkedList(productstbQuery.getResultList()));
        editorstbQuery = java.beans.Beans.isDesignTime() ? null : StorePUEntityManager.createQuery("SELECT e FROM Editorstb e");
        editorstbList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(new java.util.LinkedList(editorstbQuery.getResultList()));
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("jdbc:derby:C:\\Users\\Robert\\Documents\\NetBeansProjects\\Store\\dbStorePU").createEntityManager();
        productstbQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Productstb p");
        productstbList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productstbQuery1.getResultList();
        tbpTabs = new javax.swing.JTabbedPane();
        tbEditors = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEditors = new javax.swing.JTable();
        tbEditEditors = new javax.swing.JPanel();
        tbProducts = new javax.swing.JPanel();
        scrPane = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        tbEditProducts = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsProduct = new javax.swing.JList();
        txtStaticProductName = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        txtStaticDescription = new javax.swing.JLabel();
        txtProductName1 = new javax.swing.JTextField();
        dpDateAdded = new org.jdesktop.swingx.JXDatePicker();
        txtStaticDateAdded = new javax.swing.JLabel();
        txtStaticIsDigital = new javax.swing.JLabel();
        chkIsDigital = new java.awt.Checkbox();
        txtStaticCreatedBy = new javax.swing.JLabel();
        txtStaticPrice = new javax.swing.JLabel();
        btnNewProduct = new javax.swing.JButton();
        btnEditProduct = new javax.swing.JButton();
        btnRmProduct = new javax.swing.JButton();
        btnSearchProduct = new javax.swing.JButton();
        spnPrice = new javax.swing.JSpinner();
        spnUID = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, editorstbList, tblEditors);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totallogins}"));
        columnBinding.setColumnName("Totallogins");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${isadmin}"));
        columnBinding.setColumnName("Isadmin");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dateofbirth}"));
        columnBinding.setColumnName("Dateofbirth");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${username}"));
        columnBinding.setColumnName("Username");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(tblEditors);

        javax.swing.GroupLayout tbEditorsLayout = new javax.swing.GroupLayout(tbEditors);
        tbEditors.setLayout(tbEditorsLayout);
        tbEditorsLayout.setHorizontalGroup(
            tbEditorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbEditorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
                .addContainerGap())
        );
        tbEditorsLayout.setVerticalGroup(
            tbEditorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbEditorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpTabs.addTab("Editors", tbEditors);

        javax.swing.GroupLayout tbEditEditorsLayout = new javax.swing.GroupLayout(tbEditEditors);
        tbEditEditors.setLayout(tbEditEditorsLayout);
        tbEditEditorsLayout.setHorizontalGroup(
            tbEditEditorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        tbEditEditorsLayout.setVerticalGroup(
            tbEditEditorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        tbpTabs.addTab("Edit Editors", tbEditEditors);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, productstbList, tblProducts);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${sku}"));
        columnBinding.setColumnName("Sku");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productname}"));
        columnBinding.setColumnName("Productname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${description}"));
        columnBinding.setColumnName("Description");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${price}"));
        columnBinding.setColumnName("Price");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${isdigital}"));
        columnBinding.setColumnName("Isdigital");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dateadded}"));
        columnBinding.setColumnName("Dateadded");
        columnBinding.setColumnClass(java.util.Date.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        scrPane.setViewportView(tblProducts);

        javax.swing.GroupLayout tbProductsLayout = new javax.swing.GroupLayout(tbProducts);
        tbProducts.setLayout(tbProductsLayout);
        tbProductsLayout.setHorizontalGroup(
            tbProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPane, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
                .addContainerGap())
        );
        tbProductsLayout.setVerticalGroup(
            tbProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPane, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpTabs.addTab("Products", tbProducts);

        btnFirst.setText("<<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrevious.setText("<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText(">>");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, productstbList, lsProduct);
        bindingGroup.addBinding(jListBinding);

        jScrollPane2.setViewportView(lsProduct);

        txtStaticProductName.setText("Product Name:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lsProduct, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.description}"), txtDescription, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtStaticDescription.setText("Description:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lsProduct, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.productname}"), txtProductName1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lsProduct, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dateadded}"), dpDateAdded, org.jdesktop.beansbinding.BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        txtStaticDateAdded.setText("Date Added:");

        txtStaticIsDigital.setText("Is Digital? :");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lsProduct, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.isdigital}"), chkIsDigital, org.jdesktop.beansbinding.BeanProperty.create("state"));
        bindingGroup.addBinding(binding);

        txtStaticCreatedBy.setText("Created By User ID:");

        txtStaticPrice.setText("Price (nearest Rand) :");

        btnNewProduct.setText("Add New Product");

        btnEditProduct.setText("Edit Selected Product");

        btnRmProduct.setText("Remove Selected Product");

        btnSearchProduct.setText("Search Products");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lsProduct, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.price}"), spnPrice, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lsProduct, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.editorstb.id}"), spnUID, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout tbEditProductsLayout = new javax.swing.GroupLayout(tbEditProducts);
        tbEditProducts.setLayout(tbEditProductsLayout);
        tbEditProductsLayout.setHorizontalGroup(
            tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbEditProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(tbEditProductsLayout.createSequentialGroup()
                        .addComponent(btnFirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrevious)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext)
                        .addGap(18, 18, 18)
                        .addComponent(btnLast)))
                .addGroup(tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbEditProductsLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tbEditProductsLayout.createSequentialGroup()
                                .addGroup(tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStaticDescription)
                                    .addComponent(txtStaticDateAdded)
                                    .addComponent(txtStaticProductName)
                                    .addComponent(txtStaticIsDigital)
                                    .addComponent(txtStaticCreatedBy))
                                .addGap(29, 29, 29)
                                .addGroup(tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkIsDigital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnUID, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dpDateAdded, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProductName1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(tbEditProductsLayout.createSequentialGroup()
                                .addComponent(txtStaticPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tbEditProductsLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRmProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addComponent(btnSearchProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(312, 312, 312))))
        );
        tbEditProductsLayout.setVerticalGroup(
            tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbEditProductsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addGap(18, 18, 18)
                .addGroup(tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbEditProductsLayout.createSequentialGroup()
                        .addGroup(tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStaticProductName)
                            .addComponent(txtProductName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStaticDescription)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStaticDateAdded)
                            .addComponent(dpDateAdded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStaticIsDigital)
                            .addComponent(chkIsDigital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStaticCreatedBy)
                            .addComponent(spnUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(tbEditProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStaticPrice)
                            .addComponent(spnPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(btnNewProduct)
                        .addGap(30, 30, 30)
                        .addComponent(btnEditProduct)
                        .addGap(27, 27, 27)
                        .addComponent(btnRmProduct)
                        .addGap(27, 27, 27)
                        .addComponent(btnSearchProduct))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbpTabs.addTab("Edit Products", tbEditProducts);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpTabs)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        int size=lsProduct.getFirstVisibleIndex();
        lsProduct.setSelectedIndex(size);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        int size=lsProduct.getVisibleRowCount();
        lsProduct.setSelectedIndex(size);
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        int size=lsProduct.getSelectedIndex()+1;
        lsProduct.setSelectedIndex(size);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        int size=lsProduct.getSelectedIndex()-1;
        lsProduct.setSelectedIndex(size);
    }//GEN-LAST:event_btnPreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tblMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tblMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tblMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tblMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tblMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager StorePUEntityManager;
    private javax.swing.JButton btnEditProduct;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNewProduct;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnRmProduct;
    private javax.swing.JButton btnSearchProduct;
    private java.awt.Checkbox chkIsDigital;
    private org.jdesktop.swingx.JXDatePicker dpDateAdded;
    private java.util.List<store.Editorstb> editorstbList;
    private javax.persistence.Query editorstbQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lsProduct;
    private java.util.List<store.Productstb> productstbList;
    private java.util.List<store.Productstb> productstbList1;
    private javax.persistence.Query productstbQuery;
    private javax.persistence.Query productstbQuery1;
    private javax.swing.JScrollPane scrPane;
    private javax.swing.JSpinner spnPrice;
    private javax.swing.JSpinner spnUID;
    private javax.swing.JPanel tbEditEditors;
    private javax.swing.JPanel tbEditProducts;
    private javax.swing.JPanel tbEditors;
    private javax.swing.JPanel tbProducts;
    private javax.swing.JTable tblEditors;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTabbedPane tbpTabs;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtProductName1;
    private javax.swing.JLabel txtStaticCreatedBy;
    private javax.swing.JLabel txtStaticDateAdded;
    private javax.swing.JLabel txtStaticDescription;
    private javax.swing.JLabel txtStaticIsDigital;
    private javax.swing.JLabel txtStaticPrice;
    private javax.swing.JLabel txtStaticProductName;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
